spring.application.name=fiberman-java-backend

# FIBER
fiber.node.url=${FIBER_NODE_URL:http://127.0.0.1:8227}
fiber.node.auth-token=${FIBER_NODE_AUTH_TOKEN:}
fiber.node.timeout-seconds=${FIBER_NODE_TIMEOUT_SECONDS:30}
fiber.playground.base-url=${FIBER_PLAYGROUND_BASE_URL:http://localhost:9010}
server.port=${SERVER_PORT:9010}
