spring.application.name=fiberman-java-backend

# FIBER
fiber.node.url=http://127.0.0.1:8227
fiber.node.auth-token=
fiber.node.timeout-seconds=30
fiber.playground.base-url=http://localhost:9010
server.port=9010
